version: 2.1

orbs:
  python: circleci/python@1.4.0

workflows:
  sample:
    jobs:
      - lint
      - test

jobs:
  lint:
    docker:
      - image: cimg/python:3.9.6
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: lint
          command: pycodestyle .
  test:
    docker:
      - image: cimg/python:3.9.6
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: test
          command: pytest